### ISSUE TITLE
[Feature] Run more than one node on a server 

### ISSUE THREAD

**Issue by katedayne** [massbitprotocol/massbitroute#122]
**# Problem:** I wonder if I can run more than one node on the server.

Member: Carloes#2139 

Servers configuration:
Cpu: AMD 7402 X 2
Gpu: GeForce 3080 X2
DDR: 1T
Hard disk: 8T X24

Detail: https://discord.com/channels/835113755696037908/946026963636719648/946027171938447442

**Comment by baysao** [comment]
We do not have plan to support it, so now we closed it
