### ISSUE TITLE
Node community: CLI support more options (2 day)

### ISSUE THREAD

**Issue by baysao** [massbitprotocol/massbitroute#16]
CLI support:
- [ ] Allow Limit rate
- [ ] Allow Whitelist IP
- [ ] Allow Method Call
- [ ] Allow Origin
- [ ] Allow Useragent
- [ ] Set multiple vars

**Comment by thala321** [comment]
This issue will be tracked here https://github.com/massbitprotocol/massbitroute/issues/20
