### ISSUE TITLE
UI Portal new features

### ISSUE THREAD

**Issue by hughiephan** [massbitprotocol/massbitroute#44]
Feature: register, watch & control on UI

- [x] Provide final control  for @Duyen (2/12)
- [x] design (7/12) (@Duyen) (WIP)
- [x] FE Dev (10/12) (@mison201 ) (WIP)
  - chart & statistic  
  - summary statistic at welcome to MBR page
  - in the website page, needs the shortcut to go directly to the app (MBR, CCI, Insights)
  - amcharts map for App page https://www.amcharts.com/demos/drill-down-map/
    - click: open modal with pre-filled continent
  - BLOCKING: API create Gateway/Node: missing choose zone, get number of node in zone.
  - BLOCKING: embedded Grafana chart.

**Comment by mison201** [comment]
[FE pull request](https://github.com/massbitprotocol/mbr-app/pull/3)
